# fly.toml app configuration file generated for voli-disc-bot on 2025-11-06T20:25:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'volition-discord-bot'
primary_region = 'ord'

[build]

[env]
  NODE_ENV = 'production'

# No [http_service] needed for Discord bots (WebSocket connection only)

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
