# fly.toml app configuration file generated for voli-disc-bot on 2025-11-06T20:25:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voli-disc-bot'
primary_region = 'ord'

[build]

[env]
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
